[build-system]
requires = ["setuptools>=61.0", "versioneer[toml] @ @REPOROOT@"]
build-backend = "setuptools.build_meta"

[project]
name = "probe_basic"
authors = [
  { name="Chris Polanski", email="lcvette1@gmail.com" },
]
description = "Probe Basic - A QtPyVCP based Virtual Control Panel for LinuxCNC"
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["version"]


[tool.setuptools]
packages = [
	"debian",
	"example_gcode",
	"config",
	"config.atc_sim",
	"config.atc_sim.macros_sim_inch",
	"config.atc_sim.macros_sim_metric",
	"config.atc_sim.python",
	"config.atc_sim.vismach_parts",
	"config.probe_basic",
	"config.probe_basic.hallib",
	"config.probe_basic.python",
	"config.probe_basic.subroutines",
	"config.probe_basic_lathe",
	"config.probe_basic_lathe.hallib",
	"config.probe_basic_lathe.python",
	"config.probe_basic_lathe.subroutines",
	"probe_basic",
	"probe_basic.fonts",
	"probe_basic.images",
	"probe_basic.virtual_keyboards",
	"probe_basic_latc",
	"probe_basic_latc.images",
	"probe_basic_lathe",
	"probe_basic_lathe.images",
	"probe_basic_vertical",
	"probe_basic_vertical.images",
	"widgets",
	"widgets.atc_widget",
	"widgets.atc_widget.images",
	"widgets.conversational",
	"widgets.conversational.images",
	"widgets.lathe_tool_touch_off",
	"widgets.lathe_tool_touch_off.images"
]

[project.gui-scripts]
probe_basic = "probe_basic:main"
probe_basic_lathe = "probe_basic_lathe:main"

[project.entry-points."qtpyvcp.vcp"]
probe_basic = "probe_basic"
probe_basic_lathe = "probe_basic_lathe"

[project.entry-points."qtpyvcp.widgets"]
"probe_basic_widgets" = "widgets"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "probe_basic/_version.py"
versionfile_build = "probe_basic/_version.py"
tag_prefix = ""
parentdir_prefix = ""
