widget_named_params:
  probe_posn_only_Btn:
    enabled: 1
    name: probe_posn_only
    type: bit
    access: rw
    
  probe_tool_number_3014:
    enabled: 1
    name: probe_tool_number
    type: s32
    access: rw
    
  tool_number_entry_tool_page:
    enabled: 1
    name: tool_number_entry_tool_page
    type: s32
    access: rw